Implementation of some functions

diff --git a/libexec/poac-yaml b/libexec/poac-yaml
--- a/libexec/poac-yaml
+++ b/libexec/poac-yaml
@@ -1,54 +1,53 @@
 #!/bin/bash
 #
-# Summary: Create the poac.yml.
+# Summary: 
 # Options: <yaml-filename>
 #
 set -e
 
-
+# Inspired by https://github.com/jasperes/bash-yaml
 parse_yaml() {
-    local yaml_file=$1
-    local prefix=$2
-    local s
-    local w
-    local fs
+	local yaml_file=$1
+	local s
+	local w
+	local fs
 
-    s='[[:space:]]*'
-    w='[a-zA-Z0-9_.-]*'
-    fs="$(echo @|tr @ '\034')"
+	s='[[:space:]]*'
+	w='[a-zA-Z0-9_.-]*'
+	fs="$(echo @|tr @ '\034')"
 
-    (
-        sed -ne '/^--/s|--||g; s|\"|\\\"|g; s/\s*$//g;' \
-            -e "/#.*[\"\']/!s| #.*||g; /^#/s|#.*||g;" \
-            -e  "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
-            -e "s|^\($s\)\($w\)$s[:-]$s\(.*\)$s\$|\1$fs\2$fs\3|p" |
+	(
+		sed -ne '/^--/s|--||g; s|\"|\\\"|g; s/\s*$//g;' \
+			-e "/#.*[\"\']/!s| #.*||g; /^#/s|#.*||g;" \
+			-e  "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
+			-e "s|^\($s\)\($w\)$s[:-]$s\(.*\)$s\$|\1$fs\2$fs\3|p" |
 
-        awk -F"$fs" '{
-            indent = length($1)/2;
-            if (length($2) == 0) { conj[indent]="+";} else {conj[indent]="";}
-            vname[indent] = $2;
-            for (i in vname) {if (i > indent) {delete vname[i]}}
-                if (length($3) > 0) {
-                    vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
-                    printf("%s%s%s%s=(\"%s\")\n", "'"$prefix"'",vn, $2, conj[indent-1],$3);
-                }
-            }' |
-        sed -e 's/_=/+=/g' \
-            -e '/\..*=/s|\.|_|' \
-            -e '/\-.*=/s|\-|_|'
-    ) < "$yaml_file"
-}
-
-create_variables() {
-    local yaml_file="$1"
-    eval "$(parse_yaml "$yaml_file")"
+		awk -F"$fs" '{
+			indent = length($1)/2;
+			if (length($2) == 0) { conj[indent]="+";} else {conj[indent]="";}
+			vname[indent] = $2;
+			for (i in vname) {if (i > indent) {delete vname[i]}}
+				if (length($3) > 0) {
+					vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
+					printf("%s%s%s=(\"%s\")\n",vn, $2, conj[indent-1],$3);
+				}
+			}' |
+		sed -e 's/_=/+=/g' \
+			-e '/\..*=/s|\.|_|' \
+			-e '/\-.*=/s|\-|_|'
+	) < "$yaml_file"
 }
 
 subcommand=${0##*/poac-}
 if [[ "$1" == '--help' || "$1" == '-h' ]]; then
 	exec "${POAC_ROOT}/libexec/poac---help" $subcommand
 elif [[ "$#" == 1 ]]; then
-	parse_yaml $1
+	if [[ -f $1 ]]; then
+		eval "$(parse_yaml $1)"
+	else
+		printf "\e[1;31m$1 is not founded!\n"
+		exit 1
+	fi
 else
 	echo "poac ${subcommand}: illegal option -- $@"
 	exec "${POAC_ROOT}/libexec/poac---help" $subcommand
